export const dynamic = "force-dynamic";
import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";

// Accepts JSON payload and renders a clean branded PDF
export async function POST(req: NextRequest) {
  const body = await req.json();
  const { title, sections, meta } = body as {
    title: string;
    meta?: Record<string, string>;
    sections: Array<{
      heading?: string;
      body?: string;
      list?: string[];
      table?: Array<{ label: string; value: string }>;
    }>;
  };

  const chunks: Buffer[] = [];
  const doc = new PDFDocument({ margin: 56, size: "LETTER" });

  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  await new Promise<void>((resolve) => {
    doc.on("end", resolve);

    // ── Cover / header ──────────────────────────────────────────────
    doc
      .rect(0, 0, doc.page.width, 80)
      .fill("#1D1D1F");

    doc
      .fillColor("#ffffff")
      .font("Helvetica-Bold")
      .fontSize(11)
      .text("RUNWAY", 56, 28, { continued: false });

    doc
      .fillColor("#8E8E93")
      .font("Helvetica")
      .fontSize(9)
      .text("AI Agent Platform", 56, 44);

    doc.moveDown(3);

    // ── Title ───────────────────────────────────────────────────────
    doc
      .fillColor("#1D1D1F")
      .font("Helvetica-Bold")
      .fontSize(22)
      .text(title, 56, 110, { width: doc.page.width - 112 });

    // ── Meta block ──────────────────────────────────────────────────
    if (meta && Object.keys(meta).length > 0) {
      doc.moveDown(0.5);
      doc
        .moveTo(56, doc.y)
        .lineTo(doc.page.width - 56, doc.y)
        .strokeColor("#E5E5EA")
        .lineWidth(1)
        .stroke();
      doc.moveDown(0.5);

      for (const [k, v] of Object.entries(meta)) {
        if (!v) continue;
        doc
          .font("Helvetica-Bold")
          .fontSize(9)
          .fillColor("#8E8E93")
          .text(k.toUpperCase(), { continued: true })
          .font("Helvetica")
          .fillColor("#1D1D1F")
          .text(`  ${v}`);
      }
      doc.moveDown(0.5);
      doc
        .moveTo(56, doc.y)
        .lineTo(doc.page.width - 56, doc.y)
        .strokeColor("#E5E5EA")
        .lineWidth(1)
        .stroke();
    }

    doc.moveDown(1.5);

    // ── Sections ────────────────────────────────────────────────────
    for (const section of sections) {
      if (section.heading) {
        doc
          .font("Helvetica-Bold")
          .fontSize(12)
          .fillColor("#1D1D1F")
          .text(section.heading.toUpperCase(), {
            width: doc.page.width - 112,
          });
        doc.moveDown(0.3);
      }

      if (section.body) {
        doc
          .font("Helvetica")
          .fontSize(10)
          .fillColor("#3A3A3C")
          .text(section.body, { width: doc.page.width - 112, lineGap: 3 });
        doc.moveDown(0.8);
      }

      if (section.list && section.list.length > 0) {
        for (const item of section.list) {
          doc
            .font("Helvetica")
            .fontSize(10)
            .fillColor("#3A3A3C")
            .text(`• ${item}`, { width: doc.page.width - 120, indent: 8, lineGap: 2 });
        }
        doc.moveDown(0.8);
      }

      if (section.table && section.table.length > 0) {
        for (const row of section.table) {
          const y = doc.y;
          doc
            .font("Helvetica-Bold")
            .fontSize(9)
            .fillColor("#6E6E73")
            .text(row.label, 56, y, { width: 140 });
          doc
            .font("Helvetica")
            .fontSize(9)
            .fillColor("#1D1D1F")
            .text(row.value, 200, y, { width: doc.page.width - 256 });
          doc.moveDown(0.4);
        }
        doc.moveDown(0.6);
      }

      doc.moveDown(0.5);
    }

    // ── Footer ──────────────────────────────────────────────────────
    const footerY = doc.page.height - 40;
    doc
      .moveTo(56, footerY - 8)
      .lineTo(doc.page.width - 56, footerY - 8)
      .strokeColor("#E5E5EA")
      .lineWidth(0.5)
      .stroke();

    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor("#8E8E93")
      .text(
        `Generated by Runway AI · ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
        56,
        footerY,
        { width: doc.page.width - 112 }
      );

    doc.end();
  });

  const pdf = Buffer.concat(chunks);

  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  return new NextResponse(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${slug}.pdf"`,
      "Content-Length": String(pdf.byteLength),
    },
  });
}
